/**
 * Type definitions for Ski Analysis Pose Detection
 */

/**
 * A single pose landmark from MediaPipe
 */
export interface PoseLandmark {
  x: number;
  y: number;
  z: number;
  visibility?: number;
  presence?: number;
}

/**
 * Key landmarks used for ski analysis
 */
export interface SkiKeyLandmarks {
  leftShoulder: PoseLandmark;
  rightShoulder: PoseLandmark;
  leftHip: PoseLandmark;
  rightHip: PoseLandmark;
  leftKnee: PoseLandmark;
  rightKnee: PoseLandmark;
  leftAnkle: PoseLandmark;
  rightAnkle: PoseLandmark;
}

/**
 * Computed biomechanical metrics for a single frame
 */
export interface FrameMetrics {
  /** Timestamp in seconds */
  timestamp: number;

  /** Key landmarks for this frame */
  landmarks: SkiKeyLandmarks;

  /** Computed metrics */
  metrics: {
    /** Center of gravity height as proportion of frame height (0-1) */
    centerOfGravityHeight: number;

    /** Body tilt angle in degrees from vertical (0-90) */
    bodyTiltAngle: number;

    /** Left knee flexion angle in degrees */
    leftKneeFlexion: number;

    /** Right knee flexion angle in degrees */
    rightKneeFlexion: number;
  };
}

/**
 * Summary statistics for the entire video analysis
 */
export interface PoseAnalysisSummary {
  /** Average center of gravity height as proportion (0-1) */
  avgCenterOfGravityHeight: number;

  /** Minimum center of gravity height (lowest stance) as proportion (0-1) */
  minCenterOfGravityHeight: number;

  /** Maximum body tilt angle in degrees */
  maxBodyTilt: number;

  /** Average knee flexion angle */
  avgKneeFlexion: number;

  /** Left/right asymmetry score (0-180 degrees difference) */
  leftRightAsymmetry: number;

  /** Number of frames successfully analyzed */
  framesAnalyzed: number;

  /** Video duration in seconds */
  videoDuration: number;
}

/**
 * Complete pose analysis result
 */
export interface PoseAnalysisResult {
  /** Individual frame data */
  frames: FrameMetrics[];

  /** Summary statistics */
  summary: PoseAnalysisSummary;

  /** Metadata */
  metadata: {
    /** Source video filename */
    videoFileName: string;

    /** Frame sampling interval in seconds */
    samplingInterval: number;

    /** Model used for pose detection */
    modelType: string;

    /** Processing timestamp */
    processedAt: string;
  };
}

/**
 * Text format of pose data for LLM consumption
 */
export interface PoseDataText {
  /** Formatted frame data */
  frames: string;

  /** Formatted summary */
  summary: string;
}

/**
 * Raw MediaPipe detection result
 */
export interface MediaPipeDetectionResult {
  poseLandmarks: PoseLandmark[];
  poseWorldLandmarks: PoseLandmark[];
}

/**
 * Keyframe category types
 */
export type KeyframeCategory = 'embarrassing' | 'awesome' | 'technique';

/**
 * A single keyframe extracted from the video
 */
export interface Keyframe {
  /** Timestamp in seconds */
  timestamp: number;

  /** Formatted time string (e.g., "00:15") */
  timeFormatted: string;

  /** Base64 encoded image data (JPEG) */
  imageBase64: string;

  /** Roasting caption generated by AI */
  roastCaption: string;

  /** Category of the keyframe */
  category: KeyframeCategory;

  /** Reason for selecting this keyframe */
  reason: string;

  /** Priority (1 = highest) */
  priority?: number;
}

/**
 * A data point for center of gravity chart
 */
export interface CenterOfGravityDataPoint {
  /** Timestamp in seconds */
  timestamp: number;

  /** Normalized center of gravity height (0-1) */
  value: number;
}

/**
 * Statistics for the center of gravity chart
 */
export interface CenterOfGravityStats {
  /** Average height as proportion (0-1) */
  avgHeight: number;

  /** Minimum height (lowest stance) as proportion (0-1) */
  minHeight: number;

  /** Maximum height as proportion (0-1) */
  maxHeight: number;

  /** Range between min and max */
  range: number;
}

/**
 * Complete chart data for center of gravity visualization
 */
export interface ChartData {
  /** Center of gravity data points */
  centerOfGravity: CenterOfGravityDataPoint[];

  /** Statistics */
  stats: CenterOfGravityStats;
}

/**
 * Keyframe recommendation from AI analysis
 */
export interface KeyframeRecommendation {
  /** Recommended timestamp in seconds */
  timestamp: number;

  /** Category of the keyframe */
  category: KeyframeCategory;

  /** Reason for selecting this moment */
  reason: string;

  /** Roasting caption */
  roastCaption: string;

  /** Priority (1 = highest) */
  priority?: number;
}
